name: currency_icons
description: A flutter package to display currency flag. Just specify currency name when create a new Image.
version: 0.0.2
author: Chuan-Yen Chiang <cychiang0823@gmail.com>
homepage: https://github.com/cychiang/currency-icons

environment:
  sdk: '>=2.0.0-dev.55.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.5.2"

flutter:
  assets:
    - icons/currency/aed.png
    - icons/currency/bdt.png
    - icons/currency/bzd.png
    - icons/currency/dkk.png
    - icons/currency/gip.png
    - icons/currency/inr.png
    - icons/currency/krw.png
    - icons/currency/mga.png
    - icons/currency/nad.png
    - icons/currency/pyg.png
    - icons/currency/sll.png
    - icons/currency/ttd.png
    - icons/currency/xaf.png
    - icons/currency/afn.png
    - icons/currency/bgn.png
    - icons/currency/cad.png
    - icons/currency/dop.png
    - icons/currency/gmd.png
    - icons/currency/iqd.png
    - icons/currency/kwd.png
    - icons/currency/mkd.png
    - icons/currency/ngn.png
    - icons/currency/qar.png
    - icons/currency/sos.png
    - icons/currency/twd.png
    - icons/currency/xcd.png
    - icons/currency/all.png
    - icons/currency/bhd.png
    - icons/currency/cdf.png
    - icons/currency/dzd.png
    - icons/currency/gnf.png
    - icons/currency/irr.png
    - icons/currency/kyd.png
    - icons/currency/mmk.png
    - icons/currency/nio.png
    - icons/currency/ron.png
    - icons/currency/srd.png
    - icons/currency/tzs.png
    - icons/currency/xof.png
    - icons/currency/amd.png
    - icons/currency/bif.png
    - icons/currency/chf.png
    - icons/currency/egp.png
    - icons/currency/gtq.png
    - icons/currency/isk.png
    - icons/currency/kzt.png
    - icons/currency/mnt.png
    - icons/currency/nok.png
    - icons/currency/rsd.png
    - icons/currency/std.png
    - icons/currency/uah.png
    - icons/currency/xpf.png
    - icons/currency/ang.png
    - icons/currency/bmd.png
    - icons/currency/clp.png
    - icons/currency/ern.png
    - icons/currency/gyd.png
    - icons/currency/jmd.png
    - icons/currency/lak.png
    - icons/currency/mop.png
    - icons/currency/npr.png
    - icons/currency/rub.png
    - icons/currency/svc.png
    - icons/currency/ugx.png
    - icons/currency/yer.png
    - icons/currency/aoa.png
    - icons/currency/bnd.png
    - icons/currency/cny.png
    - icons/currency/etb.png
    - icons/currency/hkd.png
    - icons/currency/jod.png
    - icons/currency/lbp.png
    - icons/currency/mro.png
    - icons/currency/nzd.png
    - icons/currency/rwf.png
    - icons/currency/syp.png
    - icons/currency/usd.png
    - icons/currency/zar.png
    - icons/currency/ars.png
    - icons/currency/bob.png
    - icons/currency/cop.png
    - icons/currency/eur.png
    - icons/currency/hnl.png
    - icons/currency/jpy.png
    - icons/currency/lkr.png
    - icons/currency/mur.png
    - icons/currency/omr.png
    - icons/currency/sar.png
    - icons/currency/szl.png
    - icons/currency/uyu.png
    - icons/currency/zmw.png
    - icons/currency/aud.png
    - icons/currency/brl.png
    - icons/currency/crc.png
    - icons/currency/fjd.png
    - icons/currency/hrk.png
    - icons/currency/kes.png
    - icons/currency/lrd.png
    - icons/currency/mvr.png
    - icons/currency/pen.png
    - icons/currency/sbd.png
    - icons/currency/thb.png
    - icons/currency/uzs.png
    - icons/currency/awg.png
    - icons/currency/bsd.png
    - icons/currency/cup.png
    - icons/currency/fkp.png
    - icons/currency/htg.png
    - icons/currency/kgs.png
    - icons/currency/ltl.png
    - icons/currency/mwk.png
    - icons/currency/pgk.png
    - icons/currency/scr.png
    - icons/currency/tjs.png
    - icons/currency/vef.png
    - icons/currency/azn.png
    - icons/currency/btn.png
    - icons/currency/cve.png
    - icons/currency/gbp.png
    - icons/currency/huf.png
    - icons/currency/khr.png
    - icons/currency/lyd.png
    - icons/currency/mxn.png
    - icons/currency/php.png
    - icons/currency/sek.png
    - icons/currency/tnd.png
    - icons/currency/vnd.png
    - icons/currency/bam.png
    - icons/currency/bwp.png
    - icons/currency/czk.png
    - icons/currency/gel.png
    - icons/currency/idr.png
    - icons/currency/kmf.png
    - icons/currency/mad.png
    - icons/currency/myr.png
    - icons/currency/pkr.png
    - icons/currency/sgd.png
    - icons/currency/top.png
    - icons/currency/vuv.png
    - icons/currency/bbd.png
    - icons/currency/byn.png
    - icons/currency/djf.png
    - icons/currency/ghs.png
    - icons/currency/ils.png
    - icons/currency/kpw.png
    - icons/currency/mdl.png
    - icons/currency/mzn.png
    - icons/currency/pln.png
    - icons/currency/shp.png
    - icons/currency/try.png
    - icons/currency/wst.png
